### ISSUE TITLE
Assets aren't linking to vite dev server, which results in a Rails 404

### ISSUE THREAD

**Issue by arcreative** [ElMassimo/vite_rails#6]
### Description 📖

When installing on vanilla Rails (6.1.1) and installing vite_rails as documented, any import statements get rewritten to the absolute path, but without hostname and port of the vite server.  I've tried various options, but it always seems to use the absolute path to the file without rewriting correctly.

### Background 📜

As described.

### The Fix 🔨

No fix found thus far

### Screenshots 📷

Entrypoint (rewritten):
![Screen Shot 2021-01-23 at 4 01 12 PM](https://user-images.githubusercontent.com/1896026/105617606-3921ee00-5d94-11eb-9964-15352c167273.png)

JS console:
![Screen Shot 2021-01-23 at 3 59 15 PM](https://user-images.githubusercontent.com/1896026/105617594-0d9f0380-5d94-11eb-976d-cfd8da4fcdb8.png)

**Comment by ElMassimo** [comment]
Hey, thanks for reporting.

That `null` there suggests that there might be a missing configuration option.

Would you share your `config/vite.json`? Also, please run `bin/rake vite:info` and paste the result so that I can verify that you are not using a previous version.

The [example app](https://github.com/ElMassimo/vite_rails/blob/main/examples/blog/Gemfile#L9) is also running 6.1.1, so it might be related to config.

**Comment by ElMassimo** [comment]
Probably related to the latest version of vite:

```
(!) "build.base" config option is deprecated. "base" is now a root-level config option.
(!) "base" config option should start and end with "/".
```

I will update the library once Vite stabilizes and releases version 2.

For now, try using `vite: "2.0.0-beta.34"`.

**Comment by ElMassimo** [comment]
@arcreative Just released an update of `vite_rails` (`1.0.11`) and `vite-plugin-ruby` (`1.0.5`).

Please try using it with the latest `vite` (`2.0.0-beta46`), and let me know how it goes.

**Comment by arcreative** [comment]
Seems like it might be working better... but I have to rewrite a lot of stuff to find out :-)

Thanks for the quick response, will let you know what I find out when I can dig into it a bit more.

**Comment by arcreative** [comment]
@ElMassimo Any idea why I would be getting `Vue.use is not a function` when doing a standard `import Vue from 'vue'` and then trying to initiate a module?  The import looks like the following (an object with default property that corresponds to what `Vue` should be):

![Screen Shot 2021-01-25 at 10 33 33 AM](https://user-images.githubusercontent.com/1896026/105749899-e3b32180-5ef8-11eb-8837-5edb13319b9c.png)

**Comment by ElMassimo** [comment]
Hard to know without more context, but from what I see in the screenshot, it seems the object is a module (instead of the export).

Try doing the following:

```js
import { default as Vue } from 'vue'
```

or

```js
Vue.default.use(...)
```

If it works, then it means the module is not unwrapping as expected. Not sure what could cause that to happen (could be related to any Vite plugins you are using, in which case upgrading to their latest versions might be worth a try).

I have a working example with Vue [here](https://github.com/ElMassimo/vite_rails/blob/main/package/example/app/frontend/entrypoints/main.ts#L1), but it's not using the default export from Vue.

**Comment by arcreative** [comment]
Thanks again for the prompt response!  I wasn't aware of that import syntax--but it doesn't seem to work either.  I'm also a bit concerned that it's not going to work for the `vite build` version of the app as well, since there isn't actually an export on default.  I am using `vite-plugin-vue2`, since vite allegedly won't work without it, but this all seems like a bit too much going on to investigate at this point.  Perhaps when vuetify goes to Vue 3 I can use Vue 3, then maybe this will all work out.  Thank you for your time!

**Comment by ElMassimo** [comment]
Have an example running Vite with Vue 2, you can find the details in [this pull request](https://github.com/ElMassimo/pingcrm-vite/pull/1).
